name: Tag Changelog Multiline
description: Automatically generate a changelog, using the conventional commit format with multiline commit messages support
author: magicsk
branding:
  icon: align-left
  color: red
inputs:
  token:
    description: Github repository token
    required: true
  exclude_types:
    description: 'Which commit types to exclude from the changelog, comma separated string (example: "other,chore")'
    required: false
  config_file:
    description: Location of the config JSON file
    required: false
outputs:
  changelog:
    description: Generated changelog for the latest tag (multiline commit message support)
  changes:
    description: Generated changelog for the latest tag (multiline commit message support), without the version/date header
runs:
  using: node12
  main: "dist/index.js"
